dipSdk:
  DipSdkCfgFileAbsPath: "/Users/sun/go/src/github.com/Dipper-Labs/dip-bridge/config/dip_sdk.yaml"

dipChain:
  DipManagerAddr: "dip130vwjx9aednhmgv3w6xjz8e6vcesmvd2sxd96r"
  AbiFileAbsPath: "/Users/sun/go/src/github.com/Dipper-Labs/dip-bridge/contracts/dip_land_contracts/dip_manager.abi"

ethChain:
  WsEndpoint: "ws://localhost:8546"
  DipManagerAddr: "0xbfc617C5e0cC53eb9116cbbDB5D78fEfCb61425A"
  DipManagerAbi: "/Users/sun/go/src/github.com/Dipper-Labs/dip-bridge/contracts/eth_land_contracts/dip_manager.abi"
  StartBlockNumber: 1 #扫描事件的开始区块
  StartBlockNumberFromRedis: false #是否从redis加载扫描事件的开始区块，首次启动设置为false，再次启动设置为true，强制从配置文件读取设置为false
  ConfirmBlockCount: 50 #等待多少个区块确认后再扫描事件

bridge:
  detectIntervalInSeconde: 10

redis:
  Endpoint: "localhost:6379"
  Password: ""
